/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef serv_CONSTANTS_H
#define serv_CONSTANTS_H

#include "serv_types.h"

namespace Thrift {

class servConstants {
 public:
  servConstants();

};

extern const servConstants g_serv_constants;

} // namespace

#endif
